//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusUygulama.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class GünlükRapor
    {
        public int RaporID { get; set; }
        public Nullable<int> OtobusID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<decimal> ToplamHasilat { get; set; }
    
        public virtual OtobusBilgi_Tablosu OtobusBilgi_Tablosu { get; set; }
    }
}
