//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusUygulama.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OTOBUSDBEntities : DbContext
    {
        public OTOBUSDBEntities()
            : base("name=OTOBUSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GünlükRapor> GünlükRapor { get; set; }
        public virtual DbSet<Koltuklar_Tablosu> Koltuklar_Tablosu { get; set; }
        public virtual DbSet<OtobusBilgi_Tablosu> OtobusBilgi_Tablosu { get; set; }
        public virtual DbSet<OtobusKoltukDuzeni_Tablosu> OtobusKoltukDuzeni_Tablosu { get; set; }
        public virtual DbSet<Sefer_Tablosu> Sefer_Tablosu { get; set; }
        public virtual DbSet<SeferBilgisi_Tablosu> SeferBilgisi_Tablosu { get; set; }
        public virtual DbSet<Cinsiyet_Tablosu> Cinsiyet_Tablosu { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int RAPOR_BAS(Nullable<int> otobusID, Nullable<System.DateTime> tarih, Nullable<decimal> hasilat)
        {
            var otobusIDParameter = otobusID.HasValue ?
                new ObjectParameter("OtobusID", otobusID) :
                new ObjectParameter("OtobusID", typeof(int));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var hasilatParameter = hasilat.HasValue ?
                new ObjectParameter("Hasilat", hasilat) :
                new ObjectParameter("Hasilat", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RAPOR_BAS", otobusIDParameter, tarihParameter, hasilatParameter);
        }
    }
}
