//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusUygulama.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtobusKoltukDuzeni_Tablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OtobusKoltukDuzeni_Tablosu()
        {
            this.SeferBilgisi_Tablosu = new HashSet<SeferBilgisi_Tablosu>();
        }
    
        public int RezervID { get; set; }
        public Nullable<int> OtobusID { get; set; }
        public Nullable<int> KoltukID { get; set; }
    
        public virtual Koltuklar_Tablosu Koltuklar_Tablosu { get; set; }
        public virtual OtobusBilgi_Tablosu OtobusBilgi_Tablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeferBilgisi_Tablosu> SeferBilgisi_Tablosu { get; set; }
    }
}
