//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusUygulama.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeferBilgisi_Tablosu
    {
        public int InfoID { get; set; }
        public Nullable<int> RezervID { get; set; }
        public Nullable<int> KalkisYeriID { get; set; }
        public Nullable<int> VarisYeriID { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<int> CinsiyetID { get; set; }
    
        public virtual OtobusKoltukDuzeni_Tablosu OtobusKoltukDuzeni_Tablosu { get; set; }
        public virtual Sefer_Tablosu Sefer_Tablosu { get; set; }
        public virtual Sefer_Tablosu Sefer_Tablosu1 { get; set; }
        public virtual Cinsiyet_Tablosu Cinsiyet_Tablosu { get; set; }
    }
}
